### ISSUE TITLE
GENERATED MEMO TOO LONG FOR SOURCE CHAIN : ADJUST SLIP OR INPUT AMOUNT

### ISSUE THREAD

**Issue by bitdaric** [asgardex/asgardex-desktop#131]
try BTC to synth USDT.
edit: also why there is no BTC to synth BTC available?

**Comment by Thorian1te** [comment]
you are right, thats a bug fixing now.
fixed btc > btc synth. logic was filtering it out of the target assets drop down 👍 
the other one is a hmm even on [thorns](https://thornode.ninerealms.com/thorchain/doc) the issue is there. 
https://thornode.ninerealms.com/thorchain/quote/swap?from_asset=BTC.BTC&to_asset=ETH%2FUSDT-0XDAC17F958D2EE523A2206206994597C13D831EC7&amount=1000000&destination=0x1c7b17362c84287bd1184447e6dfeaf920c31bbe&streaming_interval=1&streaming_quantity=1&affiliate_bps=10&affiliate=dx
