### ISSUE TITLE
Display Savers From a Ledger

### ISSUE THREAD

**Issue by Solipsos** [asgardex/asgardex-desktop#40]
Savers with Ledger

Hello,

the savers of my ledger are not being displayed, even if I click on the Ledger box.
Also in my wallet it is not being displayed. In both cases I clicked on refresh

![Screenshot 2023-09-11 102648](https://github.com/asgardex/asgardex-desktop/assets/95902228/44ca609b-2267-4bfc-b813-d290755bce0b)
![Screenshot 2023-09-11 102746](https://github.com/asgardex/asgardex-desktop/assets/95902228/540aa061-183c-4776-94d1-2c2289976e95)

Windows 11 latest Asgardex app 1.20.4

regards

**Comment by GrassRootsCrypto** [comment]
@Solipsos 1.20.5 was released that has updated savers view logic. Please give that a try and let me know.

**Comment by GrassRootsCrypto** [comment]
We have tested with BTC and there is an error where it is not getting the correct address when trying to do a tx. 
Suspect the blank client created within the ledger logic is being used instead of the ledger address. 

![Image](https://github.com/asgardex/asgardex-desktop/assets/40199525/9860a3c1-0160-45d5-bdaf-edd243420326)

Will look to fix in the next release.

**Comment by GrassRootsCrypto** [comment]
ETH Works but
1. you need to have blind signing enabled on ledger and you need enough eth in your keystore to pay for the gas because it currently looks at your keystore address instead of the ledger address for gas. Another issue that needs to be fixed.

![Image](https://github.com/asgardex/asgardex-desktop/assets/40199525/5ff4938e-e272-49d2-ace9-8c8ea6e96181)

**Comment by GrassRootsCrypto** [comment]
working. am able to see keystore and ledger savers positions.
