### ISSUE TITLE
Add THORName Support for sending Tx (thor addresses only)

### ISSUE THREAD

**Issue by GrassRootsCrypto** [asgardex/asgardex-desktop#6]
Allow thornames to be added into the send screen and validate. 

E.g. should be able to send BTC/BTC to dx if dx is registered with a thor address. 
https://thornode.ninerealms.com/thorchain/thorname/dx

Dependant on https://github.com/xchainjs/xchainjs-lib/pull/819

**Comment by GrassRootsCrypto** [comment]
Crating new thorname causes refund

Warning
Transfer refunded: pool THOR.RUNE does not exist

Memo:
~:grc:BTC:bc1abcthor1xxxTHOR.RUNE:18462207

REFUND:abc

**Comment by GrassRootsCrypto** [comment]
Able to send RUNE and synths using tns

**Comment by Feedurhead-1** [comment]
Hey, been trying to register a thorname. The first time i tried i got a refund because it was not a valid thorname. 

but after have been trying with valid available names but it doesnt seem to take place, it simply stays waiting 

<img width="530" alt="image" src="https://github.com/asgardex/asgardex-desktop/assets/82659700/41be7e10-c388-4a9a-a41a-7e3f8166e0c1">

@GrassRootsCrypto

**Comment by Thorian1te** [comment]
Okay looks like the tx Modal in unable to pick up the txhash. 
Are you able to just close it and then search the name in the input section 
or https://thornode.ninerealms.com/thorchain/thorname/<yourthornamehere> and paste that into a new tab

**Comment by Feedurhead-1** [comment]
Yeah, but the txn doesnt go through at all so no hash is created.

**Comment by Feedurhead-1** [comment]
<img width="530" alt="image" src="https://github.com/asgardex/asgardex-desktop/assets/82659700/e718de0e-cb52-4eb0-a832-d4646f0a9cca">

after a while it finally appears like so.

**Comment by Thorian1te** [comment]
okay thanks. 

Are you able to share transaction hash if there was one 
Can you tell me the name you were trying to register
